name: Deploy Multi-Branch Pages

on:
  push:
    branches:
      - main
      - dev
      - 'feature/*'

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Checkout gh-pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: old-gh-pages

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Site
        env:
          VITE_CHARACTERS_DATA_URL: ${{ secrets.CHARACTERS_DATA_URL }}
        run: npm run build

      - name: Arrange Multi-Branch Layout
        uses: coderefinery/gh-pages-multibranch@main
        with:
          directory: dist
          default_branch: main

      - name: Deploy to GitHub Pages Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
